# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
avatar:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    panda_arm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
#      gains:
#          panda_joint1: { p: 12000000, d: 5000, i: 1.0, i_clamp: 10000 }
#          panda_joint2: { p: 30000000, d: 10000, i: 1.02, i_clamp: 10000 }
#          panda_joint3: { p: 18000000, d: 5000, i: 1.01, i_clamp: 10000 }
#          panda_joint4: { p: 18000000, d: 7000, i: 1.01, i_clamp: 10000 }
#          panda_joint5: { p: 12000000, d: 7000, i: 1.01, i_clamp: 10000 }
#          panda_joint6: { p: 7000000, d: 5000, i: 1.01, i_clamp: 10000 }
#          panda_joint7: { p: 2000000, d: 2000, i: 1.0, i_clamp: 10000 }
      constraints:
          goal_time: 2.0
          stopped_velocity_tolerance: 0
      state_publish_rate: 25
      action_monitor_rate: 20

controller_list:
  - name: avatar/panda_arm_controller
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
